import { Inter } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "./Providers";
import Footer from "@/components/footer";
import Navbar1 from "@/components/Navbar1";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Learning Managment System",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className} style={{backgroundColor:'rgb(241, 245, 249)'}}>
      <AuthProvider>
            <Navbar1/>
            {children}
            <Footer/>
      </AuthProvider>
        
      </body>
    </html>
  );
}
